package com.voiceos.action.model;

/**
 * Append-only audit event types. Enough to reconstruct an action without logs.
 */
public enum AuditEventType {
    ACTION_CREATED,
    ACTION_VALIDATED,
    IDENTITY_RESOLVED,
    IDENTITY_UNRESOLVED,
    POLICY_EVALUATED,
    POLICY_DENIED,
    APPROVAL_REQUIRED,
    AGENT_SELECTED,
    AGENT_STARTED,
    AGENT_SUCCEEDED,
    AGENT_FAILED,
    TOOL_SELECTED,
    TOOL_STARTED,
    TOOL_SUCCEEDED,
    TOOL_FAILED,
    PROVIDER_STARTED,
    PROVIDER_SUCCEEDED,
    PROVIDER_FAILED,
    VERIFICATION_STARTED,
    VERIFICATION_PASSED,
    VERIFICATION_FAILED,
    ACTION_COMPLETED,
    ACTION_FAILED,
    ACTION_REJECTED,
    ACTION_CANCELLED
}
